-- Importación única de datos históricos desde HIKMAN CAPITAL SISTEMA 2.0.xlsx
-- Generado el 31-jul-2026 a partir del Excel que subió el usuario.
-- Correr DESPUÉS de pegar el supabase/schema.sql actualizado (necesita las tablas
-- currency_bias_history y el constraint de 5 niveles en currency_bias_reasons).
-- Pegar entero en Supabase > SQL Editor > New query > Run.

-- ============================================================
-- 1) SESGOS + MOTIVOS -> currency_bias / currency_bias_history / currency_bias_reasons
-- ============================================================

-- 1) Semana actual por divisa (la más reciente de SESGOS)
insert into currency_bias (currency, current_level, current_summary, current_started_at) values ('USD', 'neutral', 'A PESAR DE LOS DATOS DE INFLACION DE LA SEMANA ANTERIOR,LOS CUALES MODIFICARON LA PREVISION DE UNA SUBIDA DE TIPOS DE INTERES, LAS SOLICITUDES POR DESEMPLEO SIGUEN MOSTRANDO UN MERCADO LABORAL SOLIDO, LOS PMIS FLASH MOSTRARON UNA ACTIVIDAD ECONOMICA MUY POSITIVA  ESPECIALMENTE EN EL SECTOR DE SERVICIOS, ASI MISMO EL REPUNTE DEL PRECIO DEL PETROLEO LE DA CIERTO SOPORTE AL DOLAR AL SER UN PAIS EXPORTADOR DEL MISMO, A SU VEZ MODIFICA LA PREVISIONES DE TIPOS YA QUE CRECEN LOS EXPECTATIVAS DE UNA INFLACION MAS ALTA ', '2026-07-27') on conflict (currency) do update set current_level = excluded.current_level, current_summary = excluded.current_summary, current_started_at = excluded.current_started_at;
insert into currency_bias (currency, current_level, current_summary, current_started_at) values ('EUR', 'neutral_alcista', 'A PESAR DE LA SUBIDA DEL PRECIO DEL PETROLEO Y LA ZONA EUROPEA SER UN PAIS DEPENDIENTE DE LA ENERGIA, EL IMPACTO NO HA SIDO TAN NEGATIVO YA QUE DICHO AUMENTO DE LA ENERGIA AUMENTA A SU VEZ LAS PREVISIONES DE TIPOS DE INTERES, A NIVEL MACROECONOMICO INDICADORES DE CONFIANZA COMO EL ZEW MOSTRARON MEJORA EN LA CONFIANZA DE LOS INVERSORES, LA DESICION DE TIPOS DEL BCE LIGERAMENTE ALCISTA CON LA PRESIDENTA LAGARDE INSISTIENDO EN QUE LOS EFECTOS DE SEGUNDA RONDA AUN NO SE HAN MATERIALIZADO, POR EL ULTIMO LOS PMIS MOSTRARON UNA RECUPERACION GLOBAL DE LA ECONOMIA LO CUAL A SU VEZ NOS DICE QUE SE EL BCE PUEDE SUBIR TIPOS SI LAS PRESIONES INFLACIONARIAS AUMENTAN SIN TENER UN EFECTO NEGATIVO A CORTO PLAZO ', '2026-07-27') on conflict (currency) do update set current_level = excluded.current_level, current_summary = excluded.current_summary, current_started_at = excluded.current_started_at;
insert into currency_bias (currency, current_level, current_summary, current_started_at) values ('CAD', 'dovish', 'SEMANA CONTUNDENTE PARA EL CAD, LOS DATOS DE INFLACION SE MODERARON CONSIDERABLEMENTE, Y EN CONSONANCIA CON EL BOC, LA INFLACION QUE VIGILA DE CERCA EL BOC (MEDIA RECORTADA-MEDIA PONDERADA), SE SITUARON POR DEBAJO DEL 2%, EN SEGUNDA INSTANCIA LA ADMINISTRACION TRUMP IMPUSO ARANCELES DEL 50% A CANADA QUE AFECTARIAN A UNOS 20.000 MILLONES DE DOLARES, LO CUAL AFIRMA COMO HA DICHO EL BOC QUE PUEDEN ESTAR DISPUESTOS A BAJAR TIPOS DE INTERES SI LAS TENSIONES COMERCIALES AUMENTAN SIGNIFICATIVAMENTE ', '2026-07-27') on conflict (currency) do update set current_level = excluded.current_level, current_summary = excluded.current_summary, current_started_at = excluded.current_started_at;
insert into currency_bias (currency, current_level, current_summary, current_started_at) values ('GBP', 'neutral', ' SEMANA PARA LA LIBRA LLENA DE MUCHA INFORMACION, LOS DATOS DE EMPLEO MOSTRARON UN CRECIMIENTO DE DE 147MIL NOMINAS, LA TASA DE DESEMPLEO DESCENDIO AL 4.9% MIENTRAS LOS SALARIOS INCLUYENDO BONUS SE RELAJARON AL 4.3%, LA INFLACION GENERAL SE MODERO AUNQUE YA DESCONTADO EN PARTE A LA CAIDA DE LOS PRECIOS DE LA ENERGIA  DEL MES ANTERIOR, MIENTRAS LA INFLACION SUBYACENTE SE MANTUVO SIN CAMBIOS, YA PARA TERMINAR LA SEMANA LOS PMIS MEJOR DE LO PREVISTO Y LAS VENTAS MINORISTAS MOSTRARON UNA GRAN MEJORA DE LA DEMANDA INTERNA ', '2026-07-27') on conflict (currency) do update set current_level = excluded.current_level, current_summary = excluded.current_summary, current_started_at = excluded.current_started_at;
insert into currency_bias (currency, current_level, current_summary, current_started_at) values ('AUD', 'neutral_alcista', 'FUERTE RECUPERACION DEL EMPLEO EN UNA DIVISA QUE YA ESTABA ENFOCADA EN LOS EFECTOS DE 3 SUBIDAS CONSECUTIVAS ESTE ANO, EL MERCADO AUN SIGUE POSICIONADO A UNA PAUSA O UNA SUBIDA DE 25PTS BASICOS ESTE ANO, LOS DATOS DE INFLACION DE ESTA SEMANA PODRIAN MODIFICAR DRASTICAMENTE ESTA LECTURA, LOS PMIS MOSTRARON UNA FUERTE MEJORA DE LA ACTIVIDAD ECONOMICA ', '2026-07-27') on conflict (currency) do update set current_level = excluded.current_level, current_summary = excluded.current_summary, current_started_at = excluded.current_started_at;
insert into currency_bias (currency, current_level, current_summary, current_started_at) values ('NZD', 'hawkish', ' LOS DATOS DE INFLACION REAFIRMARON EL SESGO ALCISTA DEL DOLAR NEOZELANDES ', '2026-07-27') on conflict (currency) do update set current_level = excluded.current_level, current_summary = excluded.current_summary, current_started_at = excluded.current_started_at;
insert into currency_bias (currency, current_level, current_summary, current_started_at) values ('CHF', 'dovish', 'SIN CAMBIOS ESTA SEMANA', '2026-07-27') on conflict (currency) do update set current_level = excluded.current_level, current_summary = excluded.current_summary, current_started_at = excluded.current_started_at;
insert into currency_bias (currency, current_level, current_summary, current_started_at) values ('JPY', 'neutral_alcista', 'SIN MUCHOS CAMBIOS RELEVANTES EN LA SEMANA EL SESGO SE MANTIENE Y SE REAFIRMA, ESPECIALMENTE LOS DATOS DE CRECIMIENTO PRELIMINARES COMO LOS PMIS, MUESTRAS UNA MEJORA EN LA ACTIVIDAD ECONOMICA, LOS DATOS DE INFLACION AUNQUE PARCIALMENTE IGUAL QUE LAS PREVISIONES MOSTRARON CIERTA RECUPERACION DE LA INFLACION SUBYACENTE (AUN POR DEBAJO DEL 2%) PERO REAFIRMA LA INTENCION DEL BOJ DE UNA SUBIDA CADA MENOS DE 6 MESES. ', '2026-07-27') on conflict (currency) do update set current_level = excluded.current_level, current_summary = excluded.current_summary, current_started_at = excluded.current_started_at;

-- 2) Motivos de la semana actual
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('MOT-260728104800-744', 'USD', 'CONFIANZA DEL CONSUMIDOR  90,8 vs 92,4 esperado', 'neutral', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('MOT-260730091331-732', 'USD', 'CORE PCE PRICE INDEX M/M 0.1% vs 0.2% esperado', 'neutral_bajista', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('MOT-260730091458-821', 'USD', 'PCE PRICE INDEX M/M -0.1% vs -0.1% esperado', 'neutral_bajista', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('MOT-260730091734-578', 'USD', 'GDP QOQ Q1 1.5% vs 2.1% esperado', 'neutral_bajista', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('MOT-260730090524-920', 'EUR', '(PIB)GDP QOQ Q2 0.4 vs 0.2% esperado', 'hawkish', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('MOT-260730090606-494', 'EUR', '(PIB)GDP YOY Q2 1.0% vs 0.5% esperado', 'hawkish', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('MOT-260730091028-474', 'EUR', 'GERMAN CPI M/M 0.8% vs 0.7% esperado', 'hawkish', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('MOT-260730091109-696', 'EUR', 'GERMAN CPI Y/Y 2.8% vs 2.7% esperado', 'hawkish', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('SES-260726192429-693-R0', 'CAD', 'CPI , CORE CPI', 'dovish', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('SES-260726192429-693-R1', 'CAD', 'VENTAS MINORISTAS', 'dovish', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('SES-260726190949-848-R0', 'GBP', 'EVOLUCIÓN TRIMESTRAL DEL EMPLEO (MENSUAL) (MAY) 147K vs 85K', 'neutral', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('SES-260726190949-848-R1', 'GBP', 'TASA DE DESEMPLEO (MAR) 4.9% vs 5%', 'neutral', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('SES-260726190949-848-R2', 'GBP', 'SALARIOS INC, BONUS 4,3% vs 4,5% ESPERADO', 'neutral', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('SES-260726190949-848-R3', 'GBP', 'CORE CPI', 'neutral', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('SES-260726190949-848-R4', 'GBP', 'CPI Y/Y JUN 2.6% vs 2.7%', 'neutral', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('SES-260726190949-848-R5', 'GBP', 'CPI M/M JUN 0.1% vs 0.1%', 'neutral', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('SES-260726190949-848-R6', 'GBP', 'PMI COMPUESTO (JUL) 52.1 vs 49.7 esperado', 'neutral', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('SES-260726190949-848-R7', 'GBP', 'VENTAS MINORISTAS', 'neutral', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('MOT-260729201320-684', 'AUD', 'IPC YOY Q2 3.9% vs 4.1%', 'dovish', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('MOT-260729201532-308', 'AUD', 'IPC MEDIO RECORTADA QOQ Q2 0.80% vs 0.9% esperado', 'dovish', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('MOT-260729201811-298', 'AUD', 'IPC MEDIO PONDERADO QOQ Q2 0.7%', 'dovish', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('MOT-260729201941-270', 'AUD', 'IPC MEDIA RECORTADA YOY Q2 3.6% vs 3.7%', 'dovish', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('MOT-260730085607-247', 'NZD', 'CONFIANZA EMPRESARIAL ANZ 56.1', 'hawkish', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('SES-260726184922-618-R0', 'JPY', 'BALANZA COMERCIAL', 'neutral_alcista', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('SES-260726184922-618-R1', 'JPY', 'PMIS', 'neutral_alcista', NULL) on conflict (id) do nothing;
insert into currency_bias_reasons (id, currency, label, color, headline_id) values ('SES-260726184922-618-R2', 'JPY', 'CPI NACIONAL', 'neutral_alcista', NULL) on conflict (id) do nothing;

-- 3) Semanas archivadas (historial)
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-MIG-A1', 'USD', 'hawkish', '', '[{"id": "SES-MIG-A1-R0", "label": "TIPOS DE INTERES", "color": "hawkish", "headlineId": null}, {"id": "SES-MIG-A1-R1", "label": "VENTAS MINORISTAS", "color": "hawkish", "headlineId": null}, {"id": "SES-MIG-A1-R2", "label": "SOLICITUDES POR DESEMPLEO", "color": "hawkish", "headlineId": null}]'::jsonb, '2026-06-22') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-MIG-B1', 'USD', 'hawkish', 'Score geopolitico: RISK ON', '[{"id": "SES-MIG-B1-R0", "label": "PMIS", "color": "hawkish", "headlineId": null}, {"id": "SES-MIG-B1-R1", "label": "PCE", "color": "hawkish", "headlineId": null}, {"id": "SES-MIG-B1-R2", "label": "GDP", "color": "hawkish", "headlineId": null}, {"id": "SES-MIG-B1-R3", "label": "SOLICITUDES POR DESEMPLEO", "color": "hawkish", "headlineId": null}, {"id": "SES-MIG-B1-R4", "label": "CONSUMER SENTIMENT", "color": "hawkish", "headlineId": null}]'::jsonb, '2026-06-29') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-260711225304-120', 'USD', 'neutral', 'Posible repocisionamiento de la proxima semana si los datos de inflacion acompañan y persiste la matiz haukish en el dolar por activo de refugio', '[{"id": "MOT-260714213221-676", "label": "CPI", "color": "dovish", "headlineId": null}, {"id": "MOT-260715084842-355", "label": "PPI", "color": "dovish", "headlineId": null}, {"id": "MOT-260716093335-131", "label": "SOLICITUDES POR DESEMPLEO", "color": "neutral_alcista", "headlineId": null}, {"id": "MOT-260716093358-216", "label": "VENTAS MINORISTAS SUBYACENTES", "color": "neutral_bajista", "headlineId": null}, {"id": "MOT-260717103924-752", "label": "PRODUCCIÓN INDUSTRIAL (ANUAL) (JUN) 1,14%", "color": "neutral", "headlineId": null}, {"id": "MOT-260717104345-662", "label": "CONFIANZA DEL CONSUMIDOR DE LA UNIVERSIDAD DE MICHIGAN  (JUL) 54,4 vs 51,0 esperado", "color": "neutral", "headlineId": null}]'::jsonb, '2026-07-12') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-260720112522-422', 'USD', 'neutral_bajista', 'SEMANA MIXTA PARA EL DOLAR MARCADA PRINCIPALMENTE POR LOS DATOS DE INFLACION MODERADOS LO CUAL REDUCEN LAS EXPECTATIVAS DE SUBIDAS DE TIPOS DE INTERES ,CAMBIOS EN LA TABLA DE PUNTOS DE ESPERAR 25PTS BASICOS O MAS A SOLO UNA SUBIDA, AUNQUE EL CONTEXTO GEOPOLITICO CON EL CONFLICTO DE ORIENTE MEDIO AYUDO A FRENAR LA CAIDA DEL DOLAR YA QUE LAS TENSIONES ENTRE EEUU E IRAN SIGUEN PRESENTES ', '[{"id": "SES-260720112522-422-R0", "label": "CPI, PPI, VENTAS MINORISTAS SUBYACENTES", "color": "neutral_bajista", "headlineId": null}]'::jsonb, '2026-07-20') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-MIG-A2', 'EUR', 'neutral_bajista', '', '[{"id": "SES-MIG-A2-R0", "label": "ZEW", "color": "neutral_bajista", "headlineId": null}, {"id": "SES-MIG-A2-R1", "label": "SALARIOS", "color": "neutral_bajista", "headlineId": null}]'::jsonb, '2026-06-22') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-MIG-B2', 'EUR', 'neutral', '', '[{"id": "SES-MIG-B2-R0", "label": "PMIS", "color": "neutral", "headlineId": null}, {"id": "SES-MIG-B2-R1", "label": "CONSUMER CLIMATE", "color": "neutral", "headlineId": null}]'::jsonb, '2026-06-29') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-260711225900-199', 'EUR', 'dovish', '/  Las actas aunq yaben parte descontado en semanas anteriores, reafirmaron una perspectiva de llevar inflacion al 2%, lo cual puede requerir subidas de tasas, descontadas en 3 subidas por mercado y 2 por BCE, se prevee que la inflacion alcance su punto maximo por perspectivas del conflicto de oriente medio', '[{"id": "MOT-260716214911-583", "label": "BALANZA COMERCIAL", "color": "dovish", "headlineId": null}, {"id": "MOT-260717103635-173", "label": "CPI GENERAL BAJO EN BASE AL CONSENSO AL IGUAL QUE LA INFLACION SUBYACENTE", "color": "neutral", "headlineId": null}]'::jsonb, '2026-07-12') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-260720113142-317', 'EUR', 'neutral_bajista', 'SABIENDO QUE EN EUROPA ES MOTOR INDUSTRIAL, LOS DATOS DE PRODUCCION AHORA EN CONTRACCION CONFIRMAN UNA DESACELERACION EN EL CRECIMIENTO, LOS DATOS DE INFLACION (FINALES) NO SORPRENDIERON SALIERON EN BASE AL CONSENSO, MOTIVO DE LA CAIDA DE LOS PRECIOS DE LA ENERGIA EL MES PASADO...... A ESPERA DE MAS CONTEXTO CON LA DESICION DE TIPOS ESTA SEMANA YA QUE EL PETROLEO VUELVE A REPUNTAR DESPUES DE QUE SE ATENUARAN LAS TENSIONES GEOPOLITICAS', '[{"id": "SES-260720113142-317-R0", "label": "PRODUCCION INDUSTRIAL, INFLACION(DESCONTADO)", "color": "neutral_bajista", "headlineId": null}]'::jsonb, '2026-07-20') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-MIG-A3', 'CAD', 'neutral_bajista', '', '[{"id": "SES-MIG-A3-R0", "label": "VENTAS MINORISTAS", "color": "neutral_bajista", "headlineId": null}, {"id": "SES-MIG-A3-R1", "label": "(DISRUPCIONES CON EL TMEC)", "color": "neutral_bajista", "headlineId": null}]'::jsonb, '2026-06-22') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-MIG-B3', 'CAD', 'dovish', '', '[{"id": "SES-MIG-B3-R0", "label": "DATOS DE INFLACION", "color": "dovish", "headlineId": null}]'::jsonb, '2026-06-29') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-260711234023-885', 'CAD', 'neutral_bajista', 'atentos a la subida del presio del petroleo derivado del conflicto medio', '[{"id": "MOT-260718195300-124", "label": "TIPOS DE INTERES", "color": "neutral", "headlineId": null}]'::jsonb, '2026-07-12') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-260720114210-931', 'CAD', 'neutral_bajista', 'COMUNICADO AMBIGUO, LIGERAMENTE DOVISH, EL BOC ELIMINA CUALQUIER REFERENCIA DE SUBIR TIPOS', '[{"id": "SES-260720114210-931-R0", "label": "TIPOS DE INTERES", "color": "neutral_bajista", "headlineId": null}]'::jsonb, '2026-07-20') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-MIG-A4', 'GBP', 'neutral_bajista', '', '[{"id": "SES-MIG-A4-R0", "label": "PRIMA POLITICA(POSIBLE DIMISION DE STARMER)", "color": "neutral_bajista", "headlineId": null}, {"id": "SES-MIG-A4-R1", "label": "DATOS DE INFLACION", "color": "neutral_bajista", "headlineId": null}, {"id": "SES-MIG-A4-R2", "label": "DATOS DE EMPLEO", "color": "neutral_bajista", "headlineId": null}, {"id": "SES-MIG-A4-R3", "label": "VENTAS MINORISTAS", "color": "neutral_bajista", "headlineId": null}, {"id": "SES-MIG-A4-R4", "label": "TIPOS DE INTERES", "color": "neutral_bajista", "headlineId": null}]'::jsonb, '2026-06-22') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-MIG-B4', 'GBP', 'neutral_bajista', '', '[{"id": "SES-MIG-B4-R0", "label": "DIMISION PACIFICA DE STARMER", "color": "neutral_bajista", "headlineId": null}, {"id": "SES-MIG-B4-R1", "label": "PMIS", "color": "neutral_bajista", "headlineId": null}]'::jsonb, '2026-06-29') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-260711230339-435', 'GBP', 'neutral_bajista', 'Farage (posible contienda con partido laborista', '[{"id": "MOT-260714214806-850", "label": "BRC RETAIL SALES", "color": "neutral_bajista", "headlineId": null}, {"id": "MOT-260716094223-426", "label": "GDP 3M/3M", "color": "neutral_alcista", "headlineId": null}, {"id": "MOT-260716214559-365", "label": "PIB: moderado / Resiliente", "color": "neutral_alcista", "headlineId": null}, {"id": "MOT-260716214725-753", "label": "Producción Industrial, dura contracción mensual (-0,5%)", "color": "dovish", "headlineId": null}]'::jsonb, '2026-07-12') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-260720114042-774', 'GBP', 'neutral_bajista', 'LIGERA MEJORA EN LOS DATOS DE CRECIMIENTO (PIB) AUNQUE COMO TAL NADA QUE MODIFIQUE EL SESGO, LAS VENTAS MINORITAS SE MODERARON CONSIDERABLEMENTE ', '[{"id": "SES-260720114042-774-R0", "label": "BRC RETAIL SALES, PIB", "color": "neutral_bajista", "headlineId": null}]'::jsonb, '2026-07-20') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-MIG-A5', 'AUD', 'neutral', '', '[{"id": "SES-MIG-A5-R0", "label": "TIPOS DE INTERES(PRUDENTE PERO RESTRICTIVO)", "color": "neutral", "headlineId": null}]'::jsonb, '2026-06-22') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-MIG-B5', 'AUD', 'neutral', '', '[{"id": "SES-MIG-B5-R0", "label": "DATOS DE INFLACION", "color": "neutral", "headlineId": null}, {"id": "SES-MIG-B5-R1", "label": "DATOS DE EMPLEO", "color": "neutral", "headlineId": null}]'::jsonb, '2026-06-29') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-260711234119-307', 'AUD', 'neutral', '', '[{"id": "MOT-260714214639-543", "label": "CONSUMER SENTIMENT", "color": "neutral_alcista", "headlineId": null}, {"id": "MOT-260714214707-111", "label": "BALANZA COMERCIA CNY", "color": "hawkish", "headlineId": null}]'::jsonb, '2026-07-12') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-260720114314-922', 'AUD', 'neutral', 'MEJORA NOTABLE EN EL SENTIMIENTO DEL CONSUMIDOR ', '[{"id": "SES-260720114314-922-R0", "label": "CONSUMER SENTIMENT", "color": "neutral", "headlineId": null}]'::jsonb, '2026-07-20') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-MIG-A6', 'NZD', 'hawkish', '', '[{"id": "SES-MIG-A6-R0", "label": "VENTAS MINORISTAS CON TARJETA DE CREDITO", "color": "hawkish", "headlineId": null}, {"id": "SES-MIG-A6-R1", "label": "FPI", "color": "hawkish", "headlineId": null}, {"id": "SES-MIG-A6-R2", "label": "BALANZA COMERCIAL", "color": "hawkish", "headlineId": null}]'::jsonb, '2026-06-22') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-MIG-B6', 'NZD', 'hawkish', '', '[{"id": "SES-MIG-B6-R0", "label": "SIN CAMBIOS EN LA SEMANA", "color": "hawkish", "headlineId": null}]'::jsonb, '2026-06-29') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-260711234348-762', 'NZD', 'hawkish', 'enn la ultima desicion de tipos de interes, se dejo la puerta abierta a proximas subida de tipos ', '[{"id": "MOT-260714214751-640", "label": "BALANZA COMERCIAL CNY", "color": "neutral_alcista", "headlineId": null}, {"id": "MOT-260714214824-937", "label": "VENTAS MINORISTAS", "color": "neutral_bajista", "headlineId": null}, {"id": "MOT-260715084930-614", "label": "BUSSINES CONFIDENCE", "color": "hawkish", "headlineId": null}]'::jsonb, '2026-07-12') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-260720114605-919', 'NZD', 'hawkish', 'MEJORA DE LA CONFIANZA EMPRESARIAL, Y DADO QUE EL NZD ES EXPORTADOR DE MATERIAS PRIMAS BLANDAS/TRIGO Y DICHOS RUBROS TUVIERON UN REPUNTE SOSTENIBLE ESTA SEMANA FAVORECEN EL SESGO', '[{"id": "SES-260720114605-919-R0", "label": "CONFIANZA EMPRESARIAL,", "color": "hawkish", "headlineId": null}]'::jsonb, '2026-07-20') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-MIG-A7', 'CHF', 'dovish', '', '[{"id": "SES-MIG-A7-R0", "label": "TIPOS DE INTERES(SCHLEGEL)", "color": "dovish", "headlineId": null}, {"id": "SES-MIG-A7-R1", "label": "PPI", "color": "dovish", "headlineId": null}]'::jsonb, '2026-06-22') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-MIG-B7', 'CHF', 'dovish', '', '[{"id": "SES-MIG-B7-R0", "label": "ZEW", "color": "dovish", "headlineId": null}]'::jsonb, '2026-06-29') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-260711234423-609', 'CHF', 'dovish', '', '[{"id": "MOT-260718195306-533", "label": "PPI", "color": "neutral_bajista", "headlineId": null}]'::jsonb, '2026-07-12') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-260720114648-933', 'CHF', 'dovish', 'SIN MUCHOS CAMBIOS, LOS DATOS SIGUEN MOSTRANDO UN ESPIRAL DESINFLACIONARIO ', '[{"id": "SES-260720114648-933-R0", "label": "PPI", "color": "dovish", "headlineId": null}]'::jsonb, '2026-07-20') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-MIG-A8', 'JPY', 'neutral', '', '[{"id": "SES-MIG-A8-R0", "label": "TIPOS DE INTERES, DATOS DE INFLACION NACIONAL", "color": "neutral", "headlineId": null}]'::jsonb, '2026-06-22') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-MIG-B8', 'JPY', 'neutral', '', '[{"id": "SES-MIG-B8-R0", "label": "DATOS DE INFLACION", "color": "neutral", "headlineId": null}, {"id": "SES-MIG-B8-R1", "label": "PMIS", "color": "neutral", "headlineId": null}]'::jsonb, '2026-06-29') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-260711230155-721', 'JPY', 'hawkish', '', '[{"id": "SES-260711230155-721-R0", "label": "PPI/ INCENTIVO DE PENSIONES POR EL GOBIERNO", "color": "hawkish", "headlineId": null}]'::jsonb, '2026-07-12') on conflict (id) do nothing;
insert into currency_bias_history (id, currency, level, summary, reasons, started_at) values ('SES-260720113733-525', 'JPY', 'neutral_alcista', 'SIN MUCHOS CAMBIOS RELEVANTES A NIVEL MACRO, DATOS DE SEGUNDO NIVEL MODERADOS Y EN CONTRACCION SIN EMBARGO NADA QUE MODIFIQUE EL SESGO INICIAL YA QUE LOS DATOS DE CRECIMIENTO IMPORTANTES RESPALDAN EL YEN JAPONES............ ESPECIAL ATENCION A LOS DATOS DE INFLACION DE ESTA SEMANA, UNOS DATOS SOLIDOS/ROBUSTOS CONFIRMARIAN UNA VISION MACRO MAS SOLIDA ', '[{"id": "SES-260720113733-525-R0", "label": "PEDIDOS DE MAQUINARIA BASICA", "color": "neutral_alcista", "headlineId": null}]'::jsonb, '2026-07-20') on conflict (id) do nothing;

-- ============================================================
-- 2) TITULARES (activos) -> headlines
-- ============================================================


insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-MIG-28', 'Trump: No estoy seguro de querer llegar a un acuerdo con los líderes iraníes. Terminemos el trabajo.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-08T00:00:00Z', 'medio', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260709224415-117', 'Trump: No creo que la guerra con Irán vuelva a empezar.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-08T00:00:00Z', 'alto', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260709224524-660', 'Trump: Irán ataca barcos por la noche, eso no me gusta.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-08T00:00:00Z', 'medio', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260709224630-908', 'China planea permitir que las principales empresas de IA compren una cantidad limitada de chips NVIDIA H200 - The Information. $NVDA', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-08T00:00:00Z', 'medio', '{"SP500"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260709224715-971', 'Trump: Quizás hagamos algunas cosas que podrían aumentar el precio del petróleo.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-08T00:00:00Z', 'medio', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260709225009-186', 'Actas de la Reserva Federal: En tales escenarios, casi todos los participantes indicaron que probablemente sería necesario un endurecimiento de la política monetaria.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-08T00:00:00Z', 'bajo', '{"USD"}', true, true) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260709230237-333', 'No se han reportado explosiones en zonas cercanas al estrecho de Ormuz - IRNA', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-09T00:00:00Z', 'bajo', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260713095743-697', 'Armada de la Guardia Revolucionaria Iraní: un buque que intentaba utilizar una ruta no autorizada en el estrecho de Ormuz fue alcanzado por un disparo de advertencia y detenido - IRIB', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-11T00:00:00Z', 'alto', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260713095817-173', 'Armada de la Guardia Revolucionaria iraní: El estrecho de Ormuz permanece cerrado hasta nuevo aviso, finaliza la injerencia estadounidense.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-11T00:00:00Z', 'alto', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260713095844-209', 'Fuerzas del Comando Central de EE. UU. inician una nueva ronda de ataques después de que el Cuerpo de la Guardia Revolucionaria Islámica atacara el buque portacontenedores m/v GFS Galaxy, con bandera chipriota: CENTCOM', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-11T00:00:00Z', 'alto', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260713100009-221', 'Guardia Revolucionaria de Irán: El ejército estadounidense llevó a cabo un ataque aéreo contra bases costeras y torres de comunicación en el sur del país.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-12T00:00:00Z', 'bajo', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260713100030-315', 'Centcom: Las fuerzas estadounidenses completan la última serie de ataques contra Irán.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-12T00:00:00Z', 'bajo', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260713100142-344', 'Ejército estadounidense: El estrecho de Ormuz está abierto a todos los buques que busquen paso legal a través de aguas internacionales.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-12T00:00:00Z', 'medio', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260713100207-637', 'Trump: El estrecho de Ormuz está abierto - Entrevista con NBC', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-12T00:00:00Z', 'bajo', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260713100315-959', 'Guardia Revolucionaria Iraní: La armada llevó a cabo anoche una operación para detener a dos buques que violaban el estrecho de Ormuz, poniendo en peligro la navegación al inutilizar sus sistemas.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-12T00:00:00Z', 'medio', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260713101235-453', 'Trump: Podría haber un cierre del gobierno en septiembre si no termina la obstrucción parlamentaria. - Fox News', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-13T00:00:00Z', 'medio', '{"USD"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260713101348-818', 'Trump sobre Irán: Seremos los guardianes del estrecho.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-13T00:00:00Z', 'medio', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260713214347-431', 'Dubái planea un nuevo puerto para evitar el Estrecho de Ormuz - FT', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-13T00:00:00Z', 'bajo', '{"OIL"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260713214521-615', 'Trump: Estados Unidos recibirá un reembolso del 20% de la carga procedente de Ormuz', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-13T00:00:00Z', 'bajo', '{"ORIENTE MEDIO"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260713215852-935', 'Waller, de la Fed: preocupado por un escenario igualmente probable de que se requiera una política más estricta. Puede que necesiten subidas si la lectura de inflación subyacente de esta semana está alta', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-13T00:00:00Z', 'medio', '{"USD"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260713220224-847', 'Los operadores valoran un 50% de probabilidad de subida de tipos de la Fed este mes', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-13T00:00:00Z', 'bajo', '{"USD"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260713220441-606', 'Andrew Burnham, del Reino Unido, recibió el respaldo de 349 diputados laboristas - PA.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-13T00:00:00Z', 'medio', '{"GBP"}', true, true) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260713221501-933', 'RESUMEN DEL DIA FINANCIAL', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-13T00:00:00Z', 'bajo', '{}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260713221535-606', 'Trump sobre Irán: Les vamos a dar un duro golpe esta noche y mañana - Hugh Hewitt Show', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-13T00:00:00Z', 'alto', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260714113653-464', 'Trump: El estrecho de Ormuz está abierto a todo el tráfico marítimo, excepto al de Irán.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-14T00:00:00Z', 'medio', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260714204705-801', 'Estados Unidos respalda el oleoducto Irak-Siria para debilitar el control iraní sobre el estrecho de Ormuz.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-14T00:00:00Z', 'bajo', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260714204838-810', 'El viceministro de Asuntos Exteriores de Irán, Gharibabadi, declaró: Según el acuerdo, las fuerzas navales de la Guardia Revolucionaria llevaron a cabo operaciones de desminado en la parte norte del estrecho de Ormuz, pero la antigua ruta del estrecho de Ormuz seguía minada.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-14T00:00:00Z', 'bajo', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260714204854-824', 'CENTCOM de EE. UU.: El ejército estadounidense está lanzando más ataques contra Irán.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-14T00:00:00Z', 'bajo', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260714204914-668', 'CENTCOM de EE. UU.: Hoy a las 3 PM ET, las fuerzas estadounidenses comenzaron a lanzar ataques adicionales contra Irán para seguir debilitando las capacidades iraníes utilizadas para atacar el transporte marítimo comercial en el estrecho de Ormuz.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-14T00:00:00Z', 'bajo', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260714204932-565', 'CENTCOM de EE. UU.: Los ataques se están produciendo mientras las fuerzas estadounidenses se preparan para reanudar el bloqueo naval contra los puertos y las zonas costeras iraníes.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-14T00:00:00Z', 'bajo', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260714205017-560', 'El viceministro de Asuntos Exteriores de Irán, Gharibabadi, declaró: "Esperamos que el alcance del conflicto no se amplíe; de ​​lo contrario, sufrirán mucho más".', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-14T00:00:00Z', 'bajo', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260714205046-810', 'El viceministro de Asuntos Exteriores de Irán, Gharibabadi, declaró que es posible que Irán retome las negociaciones y muestre flexibilidad con respecto al estrecho de Ormuz.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-14T00:00:00Z', 'bajo', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260716121231-419', 'Irán ordena a los hutíes de Yemen que cierren el paso de Bab el-Mandeb hacia el Mar Rojo si Estados Unidos ataca la red eléctrica - Fuentes', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-16T00:00:00Z', 'medio', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260717232122-830', 'Estados Unidos envía decenas de aviones cisterna más a Israel ante una posible escalada - Axios', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-17T00:00:00Z', 'medio', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260717235126-840', 'El ejército iraní ataca objetivos militares estadounidenses y depósitos de combustible en Bahréin: Televisión estatal iraní', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-17T00:00:00Z', 'medio', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260720120935-335', 'Fuente iraní de alto nivel: Los mediadores han propuesto un cese de los ataques durante 10 días para encontrar maneras de reactivar el acuerdo provisional entre Irán y Estados Unidos.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-20T00:00:00Z', 'medio', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260720121034-963', 'Los hutíes anuncian una "prohibición de navegación marítima" en Arabia Saudita.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-20T00:00:00Z', 'medio', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260720153550-258', 'Trump hará que Irán pague por las recientes muertes de soldados estadounidenses. Estos golpes devastadores continuarán hasta que Trump decida lo contrario, pero las conversaciones entre nuestros países continúan - Axios citando a un funcionario estadounidense', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-20T00:00:00Z', 'medio', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260721085314-136', 'Dos petroleros cargados con crudo saudí dan media vuelta en el Mar Rojo y se dirigen a Suez - Datos', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-21T00:00:00Z', 'medio', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260721120156-894', 'Trump: Irán quiere reunirse; No tenemos interés.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-21T00:00:00Z', 'medio', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260721120356-379', 'Trump: No hemos terminado en absoluto con Irán. No nos vamos ahora mismo; hemos tenido un gran impacto en Irán.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-21T00:00:00Z', 'medio', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260721120536-748', 'Trump: Pronto llegaremos a la zona de Pickaxe Mountain, muy intensamente.

srael cree que Irán trasladó centrifugadoras nucleares a la Montaña Pickaxe.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-21T00:00:00Z', 'medio', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260722115505-886', 'Los futuros de Wall Street (Nasdaq -0,6%, S&P 500 -0,2%) revierten la recuperación reciente antes de la entrega de resultados de Alphabet al cierre del mercado.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-22T00:00:00Z', 'medio', '{"Sector Tecnológico y Resultados de Alphabet"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260722115555-452', 'Un crudo elevado reaviva los temores de persistencia inflacionaria, impulsando al alza el rendimiento de los bonos del Tesoro (cerca de máximos de dos meses)', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-22T00:00:00Z', 'alto', '{"BRENT"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260722115731-694', 'El yen gana fuerza tras reportes de que el Banco de Japón contempla subidas de tipos de interés más agresivas para frenar la debilidad cambiaria y los riesgos inflacionarios.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-22T00:00:00Z', 'alto', '{"JPY"}', true, true) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260722115813-791', 'El rendimiento de los bonos británicos destaca positivamente tras datos de inflación más débiles de lo previsto, reduciendo la presión sobre el Bank of England (BoE) para nuevas subidas', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-22T00:00:00Z', 'alto', '{"GBP"}', true, true) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260722195728-742', 'El comandante iraní Mousavi advierte que Irán cortará la electricidad de los aliados regionales de EE. UU. si sus puentes o centrales eléctricas son atacados - Tasnim News', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-22T00:00:00Z', 'bajo', '{"MEDIO ORIENTE"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260727192025-766', 'La SNB espera mantener el tipo de interés en cero hasta finales de 2027.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-27T00:00:00Z', 'alto', '{"CHF"}', true, true) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260727192053-111', 'China comienza a producir en masa herramientas de fabricación de chips DUV locales, un avance para la industria local de chips: The Information.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-27T00:00:00Z', 'medio', '{"CHINA"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260727192113-498', 'El SNB declina comentar sobre el informe de los medios que espera mantener el tipo de interés en cero hasta finales de 2027.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-27T00:00:00Z', 'alto', '{"CHF"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260727192216-376', 'Trump: Estamos manteniendo conversaciones profundas con Irán. Si no tienen éxito, volveremos a una acción militar poderosa: el Canal 12 de Israle', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-27T00:00:00Z', 'bajo', '{"ORIENTE MEDIO"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260727192421-402', 'Trump: Irán quiere reunirse y nosotros nos estamos reuniendo. Existe la posibilidad de que podamos llegar a un acuerdo con Irán', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-27T00:00:00Z', 'bajo', '{"ORIENTE MEDIO"}', true, true) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260729210231-496', 'Trump To Fox: vamos a atacar duramente a Irán.', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-29T00:00:00Z', 'medio', '{"ORIENTE MEDIO"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260729210501-192', 'China enviará lanzacohetes a Irán
El gigante asiático vende cientos de misiles antiaéreos en un acuerdo secreto que Pekín ha negado', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-29T00:00:00Z', 'medio', '{"EEUU/CHINA"}', true, false) on conflict (id) do nothing;
insert into headlines (id, title, source, url, published_at, impact, tags, is_manual, pinned) values ('TIT-260729212837-774', 'Declaración de tipos de la Fed: El voto de la Fed a favor de la política fue de 9-3, con Hammack, Kashkari y Logan de la Fed disidentes a favor de un aumento de 25 puntos básicos', 'Hikman Capital (importado del sistema anterior)', NULL, '2026-07-29T00:00:00Z', 'alto', '{"USD"}', true, true) on conflict (id) do nothing;

-- ============================================================
-- 3) DATOS_ECO (solo indicadores de carga manual) -> indicator_overrides
-- ============================================================


insert into indicator_overrides (indicator_id, date, value) values ('ism_manuf', '2026-07-01', 53.3) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('ism_manuf_employment', '2026-07-01', 49.7) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('ism_manuf_new_orders', '2026-07-01', 56.0) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('ism_manuf_prices', '2026-07-01', 73.0) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('ism_manuf_production', '2026-07-01', 52.2) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('ism_serv', '2026-07-06', 54.0) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('ism_serv_employment', '2026-07-06', 51.2) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('ism_serv_new_orders', '2026-07-06', 55.1) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('ism_serv_prices', '2026-07-06', 67.7) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('sp_pmi_manuf', '2026-06-23', 55.7) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('sp_pmi_serv', '2026-06-23', 51.3) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('sp_pmi_composite', '2026-06-23', 52.2) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('cb', '2026-07-28', 90.8) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('adp', '2026-07-01', 98000.0) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('retail_control', '2026-07-16', 0.005) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('gdpnow', '2026-06-01', 0.03) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('eur_cpi_yoy', '2026-07-17', 0.028) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('eur_core_cpi_yoy', '2026-07-17', 0.024) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('eur_pmi_manuf_flash', '2026-07-24', 52.0) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('eur_pmi_serv_flash', '2026-07-24', 51.6) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('eur_industrial_production', '2026-06-15', 0.001) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('eur_retail_sales', '2026-07-06', 0.002) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('eur_retail_sales_yoy', '2026-07-06', 0.016) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('eur_zew_sentiment', '2026-07-21', 23.4) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('eur_consumer_confidence', '2026-04-22', -20.6) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('eur_business_confidence', '2026-06-24', 85.6) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('gbp_cpi_yoy', '2026-07-22', 0.026) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('gbp_cpi', '2026-07-22', 0.001) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('gbp_core_cpi_yoy', '2026-06-17', 0.026) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('gbp_core_cpi', '2026-06-17', 0.003) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('gbp_unemployment', '2026-07-21', 0.049) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('gbp_ccc', '2026-07-21', 6700.0) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('gbp_wage_incl_bonus_yoy', '2026-07-21', 0.043) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('gbp_wage_excl_bonus_yoy', '2026-07-21', 0.034) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('gbp_pmi_manuf_flash', '2026-07-24', 52.8) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('gbp_pmi_serv_flash', '2026-07-24', 51.8) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('gbp_retail_sales', '2026-07-24', 0.01) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('gbp_core_retail_sales', '2026-07-24', 0.011) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('gbp_gdp_mom', '2026-07-16', 0.001) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('cad_pmi_manuf', '2026-06-01', 52.9) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('cad_pmi_serv', '2026-05-05', 49.2) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('aud_business_confidence', '2026-07-13', -5.0) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('aud_pmi_manuf', '2026-07-24', 51.7) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('aud_pmi_serv', '2026-07-24', 53.0) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('nzd_unemployment', '2026-05-05', 0.053) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('nzd_unemployment', '2026-06-15', 0.051) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('nzd_business_confidence', '2026-07-29', 56.1) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('nzd_pmi_manuf', '2026-06-12', 59.7) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('nzd_pmi_manuf', '2026-06-29', 50.3) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('nzd_pmi_serv', '2026-06-29', 50.2) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('nzd_trade_balance', '2026-06-19', 800.0) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('jpy_pmi_manuf', '2026-06-30', 54.8) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('jpy_pmi_serv', '2026-07-03', 52.2) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('jpy_consumer_confidence', '2026-07-01', 33.8) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('jpy_business_confidence', '2026-06-30', 22.0) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('chf_unemployment', '2026-06-04', 0.031) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('chf_trade_balance', '2026-04-21', 3098.0) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('chf_retail_sales_yoy', '2026-07-01', 0.035) on conflict (indicator_id, date) do update set value = excluded.value;
insert into indicator_overrides (indicator_id, date, value) values ('chf_pmi_manuf', '2026-07-01', 54.3) on conflict (indicator_id, date) do update set value = excluded.value;
